---
pagetitle: "Chaya Weerasinghe - Publications"
format: html
embed-resources: true
---

```{=html}
<!--
## [Work in Progress, Under Submission or Under Revision]{style="color: grey"}

::: {style="color: black"}
1\. **Weerasinghe, C.**, Loaiza-Maya, R., Martin, G. M., & Frazier, D. T. (2023). ABC-based Forecasting in Misspecified State Space Models. arXiv preprint arXiv:2311.01021. <a class="badge rounded-pill badge-blue" href="https://arxiv.org/abs/2311.01021">LINK</a>
:::

\
\
-->
```

## [Publications]{style="color: grey"}

#### [Journal Articles]{style="color: grey"}

::: {style="color: black"}
1. **Weerasinghe, C.**, Loaiza-Maya, R., Martin, G. M., and Frazier, D. T.
(2025). ABC-based forecasting in misspecified state space models. *International Journal of Forecasting*, *41*(1), 270-289. <a class="badge rounded-pill badge-blue" href="https://www.sciencedirect.com/science/article/pii/S016920702400044X">LINK</a>

2.  **Weerasinghe, W. P. M. C. N.**, & Jayasundara, D. D. M. (2021). Modelling Pepper Export Income in Sri Lanka Using Deterministic Decomposition and Seasonal ARIMA Models. *Statistics and Applications*, *19*(2), 89-100. <a class="badge rounded-pill badge-blue" href="https://ssca.org.in/media/7_19_2_2021_SA_WPMCN__Weerasinghe_Final.pdf">LINK</a>

3.  Mishra, P., Matuka, A., Abotaleb, M. S. A., **Weerasinghe, W. P. M. C. N.**, Karakaya, K., & Das, S. S. (2021). Modeling and forecasting of milk production in the SAARC countries and China. *Modeling Earth Systems and Environment*, 1-13. <a class="badge rounded-pill badge-blue" href="https://link.springer.com/article/10.1007/s40808-021-01138-z">LINK</a>

4.  **Weerasinghe, W. P. M. C. N.**, & Jayasundara, D. D. M. (2020). Modelling and forecasting the unit cost of electricity generated by fossil fuel power plants in Sri Lanka. *International Journal of Sciences: Basic and Applied Research (IJSBAR), 51(2)*, 163-178. <a class="badge rounded-pill badge-blue" href="https://www.gssrr.org/index.php/JournalOfBasicAndApplied/article/view/11041">LINK</a>

5.  Devi, M., Rahman, U. H., **Weerasinghe, W. P. M. C. N.**, Mishra, P., Tiwari, S., & Karakaya, K. (2019). Future milk production prospects in India for various animal species using time series models. *Indian Journal of Animal Research, 1*, 6. <a class="badge rounded-pill badge-blue" href="https://www.indianjournals.com/ijor.aspx?target=ijor:ijar1&volume=56&issue=9&article=019">LINK</a>
:::

\

#### [Conference proceedings]{style="color: grey"}

::: {style="color: black"}
1.  Chandrasekara , N.V., **Weerasinghe, W. P. M. C. N.**, Basnayake B.R.P.M. (2021). Impact of COVID-19 pandemic on education and mental health of physical science undergraduates in the Faculty of Science, University of Kelaniya. *COVID 19: Impact, Mitigation, Opportunities and Building Resilience - Perspectives of global relevance based on research, experience and successes in combating COVID-19 in Sri Lanka*, 263-273, Publisher: National Science Foundation (NSF), Sri Lanka, ISBN: 978-624-5896-00-4.

2.  Saumyamala, M.G.A., **Weerasinghe, W.P.M.C.N.**, Kumara, J.L.S.M., Sachithra, S.A.L. and Chandrasekarasekara, N.V. (2019). Modelling Open Market Retail Price of Red Onions in Colombo using ARIMA-GARCH Mixed Model. *Proceedings of the 12th International Research Conference of Kothalawala Defense University, Sri Lanka*, 602-608.

3.  **Weerasinghe, W. P. M. C. N.**, & Jayasundara, D. D. M. (2019). Forecasting the Unit Cost of Electricity generated by fossil fuel using ARIMA technique: A Case Study of a Diesel/Heavy Fuel Oil power plants in Sri Lanka. *Proceedings of the 12th International Research Conference of Kothalawala Defense University, Sri Lanka*, 614-619.

4.  **Weerasinghe, W. P. M. C. N.**, & Jayasundara, D. D. M. (2019). Modelling and forecasting the income of pepper exports in Sri Lanka. *Proceedings of the 4th International Research Symposium on Pure and Applied Sciences, Faculty of Science, University of Kelaniya, Sri Lanka.*

5.  **Weerasinghe, W. P. M. C. N.**, & Jayasundara, D. D. M. (2019). Forecasting the unit cost of generation of electricity in a diesel power station using ARIMA model: A case study of a leading diesel power station in western province of Sri Lanka. *Proceedings of the 3 rd Undergraduate and First National Research Symposium, University of Ruhuna, Sri Lanka.*
:::
